# Generated by Django 4.1.10 on 2023-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=1, upload_to='movies/', verbose_name='Poster'),
            preserve_default=False,
        ),
    ]
